version: "2"
services:
  rspec:
    image: openbuildservice/frontend
    environment:
      - LANG=en_US.UTF-8
    volumes:
      - .:/obs
    depends_on:
      - db
    command: /obs/contrib/start_rspec
  db:
    image: openbuildservice/mariadb
    volumes:
      - mysql_vol:/var/lib/mysql_tmpfs/
      - .:/obs
    command: /obs/contrib/start_test_db
volumes:
  mysql_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
