version: "2"
services:
  old-test-suite:
    image: openbuildservice/old-test-suite
    volumes:
      - .:/obs_readonly:ro
    privileged: true
    depends_on:
      - db
    command: /obs/contrib/start_old_tests
  db:
    image: openbuildservice/mariadb
    volumes:
      - mysql_vol:/var/lib/mysql_tmpfs/
      - .:/obs
    command: /obs/contrib/start_test_db
volumes:
  mysql_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
