# the web client only uses the database to store jobs to do (render plots)

development:
  adapter: sqlite3
  database: db/database.db

production:
  adapter: sqlite3
  database: db/database.db

stage:
  adapter: sqlite3
  database: db/database.db

test:
  adapter: sqlite3
  database: db/database.db
