# Config options for the buildservice webclient

version: 0.3

# uncomment this option if you want to use a customized theme. See README.theme
#theme: neutral

# Enable serving of images, stylesheets, and javascripts from an asset server
# asset_host: https://static.opensuse.org/hosts/build.o.o


