# Config options for the buildservice webclient
version: 0.3

# change this option to use a customized theme. See README.theme
theme: neutral
# this is build.opensuse.org's theme
#theme: bento

# Set this when the webclient runs from a subdirectory
#relative_url_root: /stage

# Set this when the api runs from a subdirectory
#api_relative_url_root: /stage

# Exceptions get mailed to these addresses:
#exception_recipients: ['webclient_noreply@opensuse.org']
exception_recipients: []

# Use static.opensuse.org for static style content
#use_static: true
