inherit_from: .rubocop_todo.yml
AllCops:
  RunRailsCops: true
  Exclude:
    - 'tmp/**/*'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'db/**/*'

Style/CommandLiteral:
  EnforcedStyle: percent_x

Lint/EndAlignment:
  AlignWith: variable

# Someday we should add copyrights
Style/Copyright:
  Enabled: false
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: ''
