inherit_from: .rubocop_todo.yml
AllCops:
  RunRailsCops: true
  Exclude:
    - 'tmp/**/*'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'db/**/*'

Style/CommandLiteral:
  EnforcedStyle: percent_x
