production:
  features: &default
    image_templates: true
    kiwi_image_editor: true
    cloud_upload: true

development:
  features:
    <<: *default
    kiwi_image_editor: true
    cloud_upload: true

test:
  features:
    <<: *default
    kiwi_image_editor: true
    cloud_upload: true
