#exception_recipients: ['webclient_noreply@opensuse.org']

# add also webui_host setting if you want allow anonymous read access via webui
#allow_anonymous: true
#webui_host: build.opensuse.org

# should be set always
webui_url: http://localhost:3000

# make use of http://blog.lighttpd.net/articles/2006/07/22/x-sendfiles-new-friend-x-rewrite
# note that you need to enable the proxy-core option to allow this
#x_rewrite_host: localhost

# Are new users allowed to register themself ? Valid options are:
# allow: Everybody who can connect to api or webui can create an account and use the service
# confirmation: Everybody who can connect to api or webui can create an account, but admin needs to approve the usage
# deny: Only admin user can create new users
new_user_registration: allow

